Algoritmo "semnome"
Var
a,b,soma,sub,divi,mult:real
Inicio
escreval("insira um numero:")
leia(a)
escreval("insira um numero:")
leia(b)
soma<-a+b
sub<-a-b
divi<-a/b
mult<-a*b
escreva("O resultado da soma é:")
escreval(soma)
escreva("O resultado da subtração é:")
escreval(sub)
escreva("O resultado da divisão é:")
escreval(divi)
escreva("O resultado da multiplicação é:")
escreval(mult)
Fimalgoritmo