Algoritmo "semnome"
Var
   a:real
Inicio
   escreval("Digite um numero:")
   leia(a)
   se (a<100)entao
      escreval("Este numero não esta entre 100 e 200")
   senao
      se (a<=200)entao
         escreval("Este numero esta entre 100 e 200")
         se (a>200)entao
         escreval("Este numero não esta entre 100 e 200")
         fimse
         fimse
         fimse
Fimalgoritmo